server:
  port: 8087

spring:
  application:
    name: notification-service

  cloud:
    aws:
      region:
        static: ${AWS_REGION:eu-north-1}
    sqs:
      queue:
        auto-create: false

ses:
  from:
    address: ${SES_FROM_ADDRESS}

sqs:
  queue:
    name: ${AWS_SQS_QUEUE_NAME}

management:
  endpoints:
    web:
      exposure:
        include: health
