# ToDo: CI/CD to be seperated into multiple workflows for better maintainability.
name: Spring Boot Microservices CI/CD

on:
  push:
    branches:
      - deploy_to_aws
    paths:
      - backend/**
      - .github/workflows/aws_ci_cd.yml
      - pom.xml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev_aws
    strategy:
      fail-fast: false
      matrix:
        service: [ user-service, order-service, payment-service, notification-service, api-gateway, inventory-service ]
    env:
      AWS_REGION: ${{ vars.AWS_REGION || 'eu-north-1' }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      SERVICE_NAME: ${{ matrix.service }}
      CLUSTER_NAME: ${{ vars.AWS_ECS_CLUSTER_NAME || 'dev-ecs-cluster'}}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'eu-north-1' }}

      - name: Build ${{ matrix.service }}
        run: mvn -B clean spring-boot:build-image -DskipTests -pl backend/$SERVICE_NAME -Dimage.name=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/dev-$SERVICE_NAME:latest

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Push Docker Image to AWS ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/dev-$SERVICE_NAME:latest
          
      - name: deploy to AWS ECS
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service dev-$SERVICE_NAME --force-new-deployment --region $AWS_REGION