# This GitHub Actions workflow sets up AWS infrastructure using Terraform
# It triggers on pushes to the 'deploy_to_aws' branch that modify files in the 'infra/envs/' directory.
name: AWS Infrastructure Setup
on:
  push:
    branches:
      - deploy_to_aws
    paths:
      - infra/envs/**
      - .github/workflows/aws_infra_setup.yml
jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: dev_aws
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'eu-north-1' }}

      - name: Initialize Terraform
        working-directory: infra/envs/dev
        run: terraform init

      - name: Validate Terraform configuration
        working-directory: infra/envs/dev
        run: terraform validate

      - name: Plan Terraform changes
        working-directory: infra/envs/dev
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes
        working-directory: infra/envs/dev
        run: terraform apply -auto-approve tfplan